"""add_created_at_to_config_cuota

Revision ID: 5a045573aaaf
Revises: add_tipo_to_config_cuota
Create Date: 2026-05-08 22:01:01.974136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5a045573aaaf'
down_revision: Union[str, None] = 'add_tipo_to_config_cuota'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cuentas_bancarias')
    op.drop_table('directiva_curso')
    op.drop_table('colegios')
    op.add_column('config_cuotas', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('cursos', 'colegio_id')
    op.drop_column('cursos', 'nivel')
    op.drop_column('cursos', 'correo_curso')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('correo_curso', sa.VARCHAR(length=255), nullable=True))
    op.add_column('cursos', sa.Column('nivel', sa.VARCHAR(length=100), nullable=True))
    op.add_column('cursos', sa.Column('colegio_id', sa.CHAR(length=36), nullable=True))
    op.drop_column('config_cuotas', 'created_at')
    op.create_table('colegios',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=255), nullable=False),
    sa.Column('direccion', sa.VARCHAR(length=255), nullable=True),
    sa.Column('ciudad', sa.VARCHAR(length=100), nullable=True),
    sa.Column('region', sa.VARCHAR(length=100), nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('logo_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('rut', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('directiva_curso',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('curso_id', sa.CHAR(length=36), nullable=False),
    sa.Column('cargo', sa.VARCHAR(length=50), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), nullable=False),
    sa.Column('telefono', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('periodo_inicio', sa.DATE(), nullable=True),
    sa.Column('periodo_fin', sa.DATE(), nullable=True),
    sa.Column('activo', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cuentas_bancarias',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('curso_id', sa.CHAR(length=36), nullable=False),
    sa.Column('banco', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tipo_cuenta', sa.VARCHAR(length=50), nullable=False),
    sa.Column('numero_cuenta', sa.VARCHAR(length=50), nullable=False),
    sa.Column('titular', sa.VARCHAR(length=100), nullable=False),
    sa.Column('rut_titular', sa.VARCHAR(length=20), nullable=True),
    sa.Column('activa', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
