"""add_directiva_to_curso

Revision ID: add_directiva_to_curso
Revises: update_notificaciones_tipo
Create Date: 2026-05-04 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'add_directiva_to_curso'
down_revision: Union[str, None] = 'update_notificaciones_tipo'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cursos', sa.Column('directiva_tesorera', sa.String(length=255), nullable=True))
    op.add_column('cursos', sa.Column('directiva_presidenta', sa.String(length=255), nullable=True))
    op.add_column('cursos', sa.Column('directiva_secretaria', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cursos', 'directiva_secretaria')
    op.drop_column('cursos', 'directiva_presidenta')
    op.drop_column('cursos', 'directiva_tesorera')
    # ### end Alembic commands ###
