"""add_notificaciones_email

Revision ID: add_notificaciones_email
Revises: ca2536e54094
Create Date: 2026-05-04 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'add_notificaciones_email'
down_revision: Union[str, None] = 'ca2536e54094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificaciones_email',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('pago_cuota_id', sa.CHAR(length=36), nullable=False),
    sa.Column('email_destinatario', sa.String(length=255), nullable=False),
    sa.Column('asunto', sa.String(length=255), nullable=False),
    sa.Column('mensaje', sa.String(length=500), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('enviado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pago_cuota_id'], ['pagos_cuotas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificaciones_email')
    # ### end Alembic commands ###
