"""add_alumnos_cuotas

Revision ID: ca2536e54094
Revises: 001_inicial
Create Date: 2026-05-03 22:47:57.699239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ca2536e54094'
down_revision: Union[str, None] = '001_inicial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumnos',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('curso_id', sa.CHAR(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=100), nullable=False),
    sa.Column('apellido_materno', sa.String(length=100), nullable=True),
    sa.Column('rut', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config_cuotas',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('curso_id', sa.CHAR(length=36), nullable=False),
    sa.Column('año', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('curso_id', 'año', 'mes', name='uq_config_cuotas_curso_año_mes')
    )
    op.create_table('apoderados',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('alumno_id', sa.CHAR(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alumno_id')
    )
    op.create_table('pagos_cuotas',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('alumno_id', sa.CHAR(length=36), nullable=False),
    sa.Column('config_cuota_id', sa.CHAR(length=36), nullable=False),
    sa.Column('movimiento_id', sa.CHAR(length=36), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['config_cuota_id'], ['config_cuotas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movimiento_id'], ['movimientos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alumno_id', 'config_cuota_id', name='uq_pagos_cuotas_alumno_config')
    )
    op.drop_index(op.f('ix_movimientos_curso_fecha'), table_name='movimientos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_movimientos_curso_fecha'), 'movimientos', ['curso_id', 'fecha'], unique=False)
    op.drop_table('pagos_cuotas')
    op.drop_table('apoderados')
    op.drop_table('config_cuotas')
    op.drop_table('alumnos')
    # ### end Alembic commands ###
