"""update_notificaciones_email_tipo_nullable

Revision ID: update_notificaciones_tipo
Revises: add_notificaciones_email
Create Date: 2026-05-04 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'update_notificaciones_tipo'
down_revision: Union[str, None] = 'add_notificaciones_email'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support ALTER COLUMN directly, so we need to recreate the table
    
    # Create new table with the desired schema
    op.create_table('notificaciones_email_new',
        sa.Column('id', sa.CHAR(length=36), nullable=False),
        sa.Column('pago_cuota_id', sa.CHAR(length=36), nullable=True),
        sa.Column('tipo', sa.String(length=20), nullable=False, server_default='pago'),
        sa.Column('email_destinatario', sa.String(length=255), nullable=False),
        sa.Column('asunto', sa.String(length=255), nullable=False),
        sa.Column('mensaje', sa.String(length=500), nullable=False),
        sa.Column('estado', sa.String(length=50), nullable=False),
        sa.Column('enviado_en', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['pago_cuota_id'], ['pagos_cuotas.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Copy data from old table to new table
    op.execute("INSERT INTO notificaciones_email_new (id, pago_cuota_id, tipo, email_destinatario, asunto, mensaje, estado, enviado_en) SELECT id, pago_cuota_id, 'pago', email_destinatario, asunto, mensaje, estado, enviado_en FROM notificaciones_email")
    
    # Drop old table
    op.drop_table('notificaciones_email')
    
    # Rename new table to old table name
    op.rename_table('notificaciones_email_new', 'notificaciones_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create old table without tipo column and with pago_cuota_id not nullable
    op.create_table('notificaciones_email_old',
        sa.Column('id', sa.CHAR(length=36), nullable=False),
        sa.Column('pago_cuota_id', sa.CHAR(length=36), nullable=False),
        sa.Column('email_destinatario', sa.String(length=255), nullable=False),
        sa.Column('asunto', sa.String(length=255), nullable=False),
        sa.Column('mensaje', sa.String(length=500), nullable=False),
        sa.Column('estado', sa.String(length=50), nullable=False),
        sa.Column('enviado_en', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['pago_cuota_id'], ['pagos_cuotas.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Copy data from new table to old table (excluding tipo column)
    op.execute('INSERT INTO notificaciones_email_old (id, pago_cuota_id, email_destinatario, asunto, mensaje, estado, enviado_en) SELECT id, pago_cuota_id, email_destinatario, asunto, mensaje, estado, enviado_en FROM notificaciones_email WHERE pago_cuota_id IS NOT NULL')
    
    # Drop new table
    op.drop_table('notificaciones_email')
    
    # Rename old table to new table name
    op.rename_table('notificaciones_email_old', 'notificaciones_email')
    # ### end Alembic commands ###
